//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace congratulation.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class congaratulationModelContainer : DbContext
    {
        public congaratulationModelContainer()
            : base("name=congaratulationModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<uc_User> uc_UserSet { get; set; }
        public virtual DbSet<uc_CongratulationCard> uc_CongratulationCardSet { get; set; }
        public virtual DbSet<uc_Congratulation> uc_CongratulationSet { get; set; }
        public virtual DbSet<uc_Gift> uc_GiftSet { get; set; }
        public virtual DbSet<uc_Photo> uc_PhotoSet { get; set; }
    }
}
