//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace congratulation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class uc_Congratulation
    {
        public int Id { get; set; }
        public string CongratulationImageUrl { get; set; }
        public string Text { get; set; }
        public string Who { get; set; }
    
        public virtual uc_CongratulationCard uc_CongratulationCard { get; set; }
    }
}
