//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace congratulation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class uc_CongratulationCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public uc_CongratulationCard()
        {
            this.uc_Congratulation = new HashSet<uc_Congratulation>();
            this.uc_Gift = new HashSet<uc_Gift>();
            this.uc_Photo = new HashSet<uc_Photo>();
        }
    
        public int Id { get; set; }
        public string HeaderText { get; set; }
        public string HeaderBackgroundImage { get; set; }
        public string Whom { get; set; }
        public string HeaderImageUrl { get; set; }
    
        public virtual uc_User uc_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<uc_Congratulation> uc_Congratulation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<uc_Gift> uc_Gift { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<uc_Photo> uc_Photo { get; set; }
    }
}
