//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace congratulation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class uc_Gift
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public uc_Gift()
        {
            this.uc_CongratulationCard = new HashSet<uc_CongratulationCard>();
        }
    
        public int Id { get; set; }
        public string GiftImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<uc_CongratulationCard> uc_CongratulationCard { get; set; }
    }
}
